#Drew Goldman
#dag5wd
#11/17/2020
#Makefile

CXX	= clang++

CXXFLAGS  = -Wall -O2

DEBUG	= -g

OFILES	  = traveling.cpp middleearth.cpp

.SUFFIXES: .o .cpp

main:	   $(OFILES)
	   $(CXX) $(OFILES)
	   doxygen